In [0]:
#@Gaya.ia CHATTERBOT #Gaia is a psychological personal assistant
####import os
#CODE EXEMPLE 
'''import time

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options   

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import ListTrainer
'''

In [0]:
'''chatbot = ChatBot("Gaia")
trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train("chatterbot.corpus.portuguese")
trainerer = ListTrainer(chatbot)

dir_path = os.getcwd()

driver = webdriver.Chrome(dir_path+'chromedriver')
driver.get('https://web.whatsapp.com/')
driver.implicitly_wait(18)

def pegaConversa(): 
    try:
        post = driver.find_element_by_class_name('_3zb-j')
        ultimo = len(post) -1
        texto = post[ultimo].find_element_by_css_selector('span.selectable-text').text
        return texto
    except: 
        pass    

def enviaMensagem(mensagem):
    caixa_de_texto = driver.find_element_by_class_name('_2s1vp')
    valor = '*Gaya: * '+str(mensagem)
    for part in valor.split('\n'):
        caixa_de_texto.send_keys(part)
        ActionChains(driver).key_down(Keys.SHIFT).key_down(Keys.ENTER).key_up(Keys.SHIFT).perform()
    time.sleep(0.5)
    botao_enviar = driver.find_element_by_class_name('_35ew6')
    botao_enviar.click()

def treinar(mensagem):
    resposta = 'Como respondo isso? Você poderia me ensinar?"'+str(mensagem)+'"'
    enviaMensagem(resposta)
    novo = []
    try:
        while True:
            ultima = pegaConversa()
            if ultima =="!":
                enviaMensagem("Voce desativou minha função de aprendizado")
                break 
            elif ultima.replace(';','') != '' and ultima != mensagem and ultima[0] == ";" :
                auxiliar = ultima 
                print(mensagem.lower().strip())
                print(ultima.replace().lower().strip())
                novo.append(mensagem.lower().strip())
                novo.append(ultima.replace().lower().strip())
                trainerer.train(novo)
                enviaMensagem("Obrigada por me ensinar!")
                break
    except: 

'''

In [8]:
import pandas as pd  
df = pd.read_csv('data.csv')
df

                Timestamp  Age  ... obs_consequence comments
0     2014-08-27 11:29:31   37  ...              No      NaN
1     2014-08-27 11:29:37   44  ...              No      NaN
2     2014-08-27 11:29:44   32  ...              No      NaN
3     2014-08-27 11:29:46   31  ...             Yes      NaN
4     2014-08-27 11:30:22   31  ...              No      NaN
...                   ...  ...  ...             ...      ...
1254  2015-09-12 11:17:21   26  ...              No      NaN
1255  2015-09-26 01:07:35   32  ...              No      NaN
1256  2015-11-07 12:36:58   34  ...              No      NaN
1257  2015-11-30 21:25:06   46  ...              No      NaN
1258  2016-02-01 23:04:31   25  ...              No      NaN

[1259 rows x 27 columns]